repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
   - id: nbqa-pyupgrade
     additional_dependencies: [jupytext, pyupgrade]
     args: [--py39-plus, --nbqa-shell]
   - id: nbqa-black
     additional_dependencies: [jupytext, black]
     args: [--nbqa-shell]
